### ISSUE TITLE
Menu not drawing.

### ISSUE THREAD

**Issue by 29380482390** [ChoZenTime/csgo-cheat-pasted-by-choZen#2]
so i just deleted the code from tabs bc i wante to redraw the menu, but the menu is not drawing, i checked the default version ( without the tabs being deleted ), and it's also not drawing, do i have to do something special to draw the menu? ( when i press insert the menu is there i think but it's invisible, like i can't click anything bc the menu is open )
https://youtu.be/k09Zq0lSQrA ( video showcasing the problem, also sorry for the quality, i just recorded it with sharex )

**Comment by ChoZenTime** [comment]
in hooks.cpp
present and rest hooks are needed for menu


maybe you deleted   in menu.cpp
if (opened)
ImGui::PushFont(font_menu);

what code for tabs did you deleted
upload  your menu.cpp to pastebin

**Comment by 29380482390** [comment]
the thing is, the menu is not drawing even if i just compile a clean source, the video that i added to the issue was on clean source, nothing was changed in it

**Comment by ChoZenTime** [comment]
maybe the injector try with my injector and dll ?
https://gofile.io/d/zIPBhp 
and tell me if its working   (dis is a clean dll version without junk dont use in mm  the injector is one of my version of randoinjector

if its not working it must be a csgo config problem here a pic of me config
![ooooo](https://user-images.githubusercontent.com/37809871/84789258-5584cd80-aff0-11ea-8e2d-68e884d212ea.jpg)

**Comment by ChoZenTime** [comment]
on sidenot is this solaris-theme from linux terminal in windows in VS  ^^?

**Comment by 29380482390** [comment]
it is dracula theme, i just use dracula for almost everything,
anyways - changing injector did not help, nor using the .dll that you send...
maybe it's because im in fullscreen windowed?

**Comment by 29380482390** [comment]
changing to fullscreen does not help..

**Comment by ChoZenTime** [comment]
hmm i use the same hooking and function like og aristios it should be no problem to show the menu  .
i use nvidia hope its not a driver thing ?
i downloaded the repo fresh and test not that i fucked up mom

**Comment by 29380482390** [comment]
are you using launch options like disable_d3d9ex or something? maybe this is the problem? i remember using old aristois and it was working without problems

**Comment by ChoZenTime** [comment]
tested the repo everthing working fine. i looked in the code it use IDirect3DDevice9 to draw imgui  = reinstall/update your direct x maybe it helps

**Comment by ChoZenTime** [comment]
no start parameter needed  ^^  disable_d3d9ex  was a getto-fix for green/dark skins bug    ( you dont need this anymore i fixed it in source)

**Comment by 29380482390** [comment]
my directx is updated, i really can't think of anything since i've tested a clean source, i tested the injector + dll that you sent me, my csgo is clean, no parameters at all - and i still cannot see the menu

**Comment by ChoZenTime** [comment]
what the fuck^^  maybe monitor res.  make it bigger / smaller dont know maybe the menu is opening in a not seen edge

**Comment by 29380482390** [comment]
literally no clue, tried changing windowpos, changing what's being drawn - still nothing, can't think of anything...

**Comment by ChoZenTime** [comment]
i changed the hooking order a lil download the new and tell me if it helped

**Comment by 29380482390** [comment]
I literally turned off my second monitor, it helped... so it tries to draw it on the wrong monitor...

**Comment by ChoZenTime** [comment]
^_^  nice

**Comment by 29380482390** [comment]
but i still need a fix, since i can't do stuff without my 2nd monitor :/

**Comment by ChoZenTime** [comment]
i think the new csgo settings for triple-monitior mode fucked the code up  i look into this but

**Comment by ChoZenTime** [comment]
1.:: whenn you safe a config it saves the pos of the menu maybe you  load the setting with second monitor , after this you can switch the second monitor on.

2 and best .:: you can play with imgui ->    SetNextWindowPos()      SetNextWindowSize()     mod the pos/size  so the menu is show on the main screen of your main monitor with both on

**Comment by 29380482390** [comment]
now it doesn't want to draw even with monitor turned off... it's fucking weird, also playing with setnextwindowpos doesn't really help

**Comment by 29380482390** [comment]
i literally tried moving the window on x axis every 500 from -5000 to 5000, and i did not see the menu appear even once.

**Comment by ChoZenTime** [comment]
try with csgo setting trible monitor mode on

**Comment by 29380482390** [comment]
i had to turn on csgo with both monitors on, then turn the left one off, and then load. this made the menu visible, also saving config does not save the menu position

**Comment by ChoZenTime** [comment]
hmm ok have no time for a good code look , at weekend i check how imgui detects the monitor etc maybe with luck i can update it

**Comment by ChoZenTime** [comment]
sry for no quick fix

**Comment by 29380482390** [comment]
it's still not consistent and works like once in few tries, thank for at least trying to help, i guess the best only thing if this will not be only my problem( imma make my friends who have more than 1 monitor test it, if they will also have the problem ), imma just try to transfer it to surface like some nerd recommend me.
